#!/bin/bash

function link()
{
    local tar="$PWD/$2"
    local src="$HOME/$1"

    local msg color

    if [[ ! -e "$tar" ]]; then
        color=1
        msg="link target not found"
    elif [[ ! -e "$src" ]]; then
        ln -s "$tar" "$src"

        color=2
        msg="successfully installed"
    elif [[ ! -h "$src" ]]; then
        color=3
        msg="not a symlink"
    else
        local sym="$(readlink "$src")"
        if [[ "$tar" != "$sym" ]]; then
            color=4
            msg="linked to $sym"
        else
            # already installed
            return 0
        fi
    fi

    tput bold
    printf "%-20s" "$1"
    tput setaf $color
    echo "$msg"
    tput sgr0
}

link .Xresources xorg/Xresources
link .bash_profile bash/bash_profile 
link .bashrc bash/bashrc 
link .config/git git 
link .config/i3 i3 
link .config/i3status i3status 
link .config/nvim vim 
link .config/termite termite
link .config/zathura zathura 
link .flake8 vim/flake8 
link .inputrc readline/inputrc
link .pylintrc vim/pylintrc 
link .ssh ssh 
link .tern-config vim/tern-config 
link .tmux.conf tmux/tmux.conf
link .vim vim 
link .vimrc vim/init.vim 
link .xinitrc xorg/xinitrc
link .zprofile zsh/zprofile 
link .zshenv zsh/zshenv 
link .zshrc zsh/zshrc 
