#!/usr/bin/env bash

set -o noclobber -o noglob -o nounset -o pipefail
IFS=$'\n'

SCREENSHOT_PATH="$HOME/pictures/screenshot.png"
SCREENSHOT_MIME='image/png'

msg() {
    local title="$1"
    local msg="${2:-}"
    notify-send --urgency=low --app-name="$(basename "$0")" "$title" "$msg"
}

die() {
    msg error "$1"
    exit
}

cmd="$1"

case "$cmd" in
    screenshot)
        region="$2"
        case "$region" in
            root) opts=(-window root) ;;
            rect) opts=() ;;
            *) die "unknown region '$region'" ;;
        esac
        import "${opts[@]}" "$SCREENSHOT_PATH"
        xclip -selection clipboard -target "$SCREENSHOT_MIME" "$SCREENSHOT_PATH"
        msg screenshot 'copied to clipboard'
        ;;
    exec)
        IFS=$' \n' read -r -d '' -a links <<< "$(xclip -selection clipboard -o)"

        case "${links[0]}" in
            https://www.youtube.com/watch\?v=*|https://youtu.be/*|https://www.twitch.tv/*)
                msg video
                mpv "${links[@]}" || die "mpv failed"
                ;;
            magnet:\?*)
                args=()
                for link in "${links[@]}"; do
                    # XXX: transmission manpage is wrong,
                    # '--add' must be prepended to every link/file
                    args+=(--add "$link")
                done
                res="$(transmission-remote "${args[@]}")" || die "$res"
                msg magnet "downloading ${#links[@]} files"
                ;;
            *)
                die "unknown link '${links[0]}'"
                ;;
        esac
        ;;
    *)
        die "unknown command '$cmd'"
        ;;
esac
