#!/usr/bin/env bash

set -o errexit -o noclobber -o noglob -o nounset -o pipefail
IFS=$'\n'

SCREENSHOT_PATH="$HOME/pictures/screenshot.png"
SCREENSHOT_MIME='image/png'

msg() {
    local title="$1"
    local msg="${2:-}"
    notify-send --urgency=low --app-name="$(basename "$0")" "$title" "$msg"
}

die() {
    msg error "$1"
    exit
}

cmd="$1"

case "$cmd" in
    screenshot)
        region="$2"
        case "$region" in
            root) opts=(-window root) ;;
            rect) opts=() ;;
            *) die "unknown region '$region'" ;;
        esac
        import "${opts[@]}" "$SCREENSHOT_PATH"
        xclip -selection clipboard -target "$SCREENSHOT_MIME" "$SCREENSHOT_PATH"
        msg screenshot 'copied to clipboard'
        ;;
    exec)
        link=$(xclip -selection clipboard -o)

        case "$link" in
            https://www.youtube.com/watch\?v=*|https://youtu.be/*|https://www.twitch.tv/*|/*.mpv)
                msg video
                mpv "$link" || die "mpv failed"
                ;;
            magnet:\?*|/*.torrent)
                for url in $link; do
                    res="$(transmission-remote -a "$url")" || die "$res"
                done
                msg magnet
                ;;
            *)
                die "unknown link '$link'"
                ;;
        esac
        ;;
    *)
        die "unknown command '$cmd'"
        ;;
esac
