#!/usr/bin/env bash

set -o errexit -o noclobber -o noglob -o nounset -o pipefail
IFS=$'\n'

NAME=scratch

tmux new-session -d -s "$NAME"
tmux new-window -d -t "$NAME:" newsboat
# tmux new-window -d -c ~/projects/devdocs ~/.rbenv/shims/rackup
# tmux new-window -d mpv --shuffle --no-audio-display --volume=50 --pause ~/music/osu
# tmux new-window -d -c ~/projects/mpv-chat ./start.py start
tmux attach-session -t "$NAME"
