#!/usr/bin/env bash

set -o noclobber -o noglob -o nounset -o pipefail
IFS=$'\n'

tmux new-session -d -s scratch
tmux new-window -d newsboat
tmux new-window -d -c ~/projects/devdocs ~/.rbenv/shims/rackup
tmux new-window -d mpv --shuffle --no-audio-display --volume=50 --pause ~/music/osu
tmux attach-session
