#!/usr/bin/env bash

set -o noclobber -o noglob -o nounset -o pipefail
IFS=$'\n'

NAME=scratch

sleep 1

tmux new-session -d -s "$NAME"
%% for scratch cmd [
tmux new-window -d -t "$NAME:" {{cmd}}
%% ]
tmux attach-session -t "$NAME"
