#!/bin/bash

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "usage: $0 suite [program]" >&2
    exit 2
fi

shopt -s nullglob

list() {
    for f in *.in *.args; do
        tst="${f%.*}"

        if [ -e "$tst.err" ]; then
            continue
        fi

        if [ ! -e "$tst.in" ]; then
            touch "$tst.in"
        fi

        echo "$tst"
    done
}

suite=$1
program=$2
zip="$(basename $(pwd)).zip"

list | sort -u > "$suite"

if [ "$program" ] && ! runSuite "$suite" "$program"; then
    exit 1
fi

rm -f "$zip"
zip -q "$zip" "$suite" $(cat "$suite" | sed 's/$/.*/g')
