# -*- mode: sh -*-

# auto start X
if [[ -z "$DISPLAY" && -n "$XDG_VTNR" && "$XDG_VTNR" -eq 1 ]] &&
    (( $+commands[startx] )); then
    exec startx
fi

if [[ -f ~/.profile ]]; then
    source ~/.profile
fi

source $DOT/shell/path

# auto start tmux
if [[ -n "$SSH_CONNECTION" && -z "$TMUX" ]] && (( $+commands[tmux] )); then
    if tmux attach || tmux new -s dev; then
        exit
    fi
fi

# vim: ft=zsh
