if [[ -f ~/.profile ]]; then
    source ~/.profile
fi

source ~/.dotfiles/common/path

# auto start X
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
    exec startx
fi

# auto start tmux
if [[ -n "$SSH_CONNECTION" && -z "$TMUX" ]]; then
    exec tmux new -A -s develop
fi

# vim: ft=zsh
