#!/bin/zsh

# --- history ---
setopt appendhistory histignorealldups histignorespace sharehistory

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000


# --- directory ---
setopt autocd


# --- tools ---
autoload -Uz run-help
if (( $+aliases[run-help] )); then
    unalias run-help
fi
alias help='run-help'

autoload -Uz zmv
alias zmv='noglob zmv'


# --- fpath ---
fpath=($DOT/zsh/completions $fpath)


# --- customizations ---
source $DOT/zsh/title.zsh
source $DOT/zsh/prompt.zsh
source $DOT/zsh/keybinds.zsh
source $DOT/zsh/completions.zsh


# --- aliases ---
%% for alias name value [
alias -- {{name}}='{{value}}'
%% ]


# --- common ---
source $DOT/shell/functions
source $DOT/shell/completions


# --- disable Ctrl-S freezing terminal ---
ttyctl -f


# --- plugins ---
if [[ -r /usr/share/doc/pkgfile/command-not-found.zsh ]]; then
    source /usr/share/doc/pkgfile/command-not-found.zsh
fi


# --- zplug ---
ZPLUG_HOME=$HOME/.config/zsh/zplug
if [[ -r $ZPLUG_HOME/init.zsh ]]; then
    ZPLUG_LOADFILE=$DOT/zsh/plugins.zsh
    source $ZPLUG_HOME/init.zsh
    zplug load
fi
