#!/bin/bash

export PATH="{{ for path dir [ }}{{dir}}:{{ ] }}$PATH"

eval "$(dircolors -b)"

%% for env var val [
export {{var}}="{{val}}"
%% ]

if [[ -f ~/.profile ]]; then
    source ~/.profile
fi

if [[ -f ~/.bashrc ]]; then
    source ~/.bashrc
fi
