#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ -f /etc/bash.bashrc ]]; then
    source /etc/bash.bashrc
fi

# history
export HISTCONTROL=ignoreboth:erasedups

# common
source ~/.dotfiles/common/aliases
source ~/.dotfiles/common/functions

# customizations
source ~/.dotfiles/bash/aliases.bash
source ~/.dotfiles/bash/prompt.bash

if [[ -f ~/.dotfiles/bash/bashrc.local ]]; then
    source ~/.dotfiles/bash/bashrc.local
fi
