#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ -f /etc/bash.bashrc ]]; then
    source /etc/bash.bashrc
fi

# directory
shopt -s autocd
shopt -s globstar

# history
export HISTCONTROL=ignoreboth:erasedups

# customizations
source "$DOT/bash/prompt.bash"

# aliases
%% for alias name value [
alias -- {{name}}="{{value}}"
%% ]

# common
source "$DOT/shell/functions"
source "$DOT/shell/completions"

# disable Ctrl-S freezing terminal
stty -ixon

# plugins
plug() {
    local plugin="$1"
    if [[ -r "/usr/share/$plugin" ]]; then
        source "/usr/share/$plugin"
    fi
}
plug 'bash-completion/bash_completion'
plug 'doc/pkgfile/command-not-found.bash'
unset plug

# local
if [[ -f "$DOT/bash/bashrc.local" ]]; then
    source "$DOT/bash/bashrc.local"
fi
