if [[ -f ~/.profile ]]; then
    source ~/.profile
fi

if [[ -f ~/.bashrc ]]; then
    . ~/.bashrc
fi

# start zsh if in ssh
if [[ -n "$SSH_CONNECTION" ]]; then
    exec zsh -
fi

source ~/.dotfiles/common/env
