# start zsh if in ssh
if [[ -n "$SSH_CONNECTION" ]]; then
    exec zsh -
fi

if [[ -f ~/.profile ]]; then
    source ~/.profile
fi

if [[ -f ~/.bashrc ]]; then
    . ~/.bashrc
fi

source ~/.dotfiles/common/path
source ~/.dotfiles/common/env

# vim: ft=sh
